name: CI
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-java@v4
              with:
                  distribution: temurin
                  java-version: '8'
            - name: Install Maven 3.0.5
              run: mvn wrapper:wrapper -Dmaven=3.0.5
            - name: Install with the release profile
              run: ./mvnw -f test/pom.xml install -Prelease
            - name: Build Maven site
              run: ./mvnw -f test/pom.xml site

